// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestExamen.Models;

#nullable disable

namespace TestExamen.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestExamen.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("PracticalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PresentationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TheoryScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGrade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            PracticalScore = 14.0m,
                            PresentationScore = 3.8m,
                            StudentId = 1,
                            SubmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TheoryScore = 16.5m,
                            TotalGrade = 34.3m
                        },
                        new
                        {
                            ProjectId = 2,
                            PracticalScore = 16.5m,
                            PresentationScore = 4.5m,
                            StudentId = 2,
                            SubmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TheoryScore = 18m,
                            TotalGrade = 39m
                        },
                        new
                        {
                            ProjectId = 3,
                            PracticalScore = 13.0m,
                            PresentationScore = 3.2m,
                            StudentId = 3,
                            SubmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TheoryScore = 14.5m,
                            TotalGrade = 4.0m
                        },
                        new
                        {
                            ProjectId = 4,
                            PracticalScore = 15.5m,
                            PresentationScore = 4.0m,
                            StudentId = 2,
                            SubmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TheoryScore = 17.0m,
                            TotalGrade = 36.5m
                        },
                        new
                        {
                            ProjectId = 5,
                            PracticalScore = 17.5m,
                            PresentationScore = 4.8m,
                            StudentId = 1,
                            SubmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TheoryScore = 19.0m,
                            TotalGrade = 41.3m
                        });
                });

            modelBuilder.Entity("TestExamen.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StudentName = "Van Damme, Lisa"
                        },
                        new
                        {
                            StudentId = 2,
                            StudentName = "Janssens, Thomas"
                        },
                        new
                        {
                            StudentId = 3,
                            StudentName = "Peeters, Emma"
                        });
                });

            modelBuilder.Entity("TestExamen.Models.Project", b =>
                {
                    b.HasOne("TestExamen.Models.Student", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TestExamen.Models.Student", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
